services:
  admin-backend:
    build: ./admin-backend
    container_name: bestar_admin_backend
    restart: always
    env_file:
      - ./admin-backend/.env
    volumes:
      - ./admin-backend/data:/app/data
    expose:
      - "8000"

  admin-frontend:
    build: ./admin-frontend
    container_name: bestar_admin_frontend
    restart: always
    ports:
      - "3005:80"
    depends_on:
      - admin-backend
